package actions.scm

case class OrderPayload(
                         id: String,
                         externalOrderId: String,
                         customerOrderId: String,
                         customerOrderCreatedOn: String,
                         promisedDeliveryDate: String,
                         source: String,
                         pharmacistName: String,
                         rpNumber: String,
                         customerName: String,
                         customerMobile: String,
                         customerEmail: String,
                         patientName: String,
                         doctorName: String,
                         storeId: String,
                         storeName: String,
                         warehouseId: Double,
                         pickerTaskId: String,
                         trayId: String,
                         address: Address,
                         items: String,
                         pickedItems: List[PickedItems],
                         discountPercentage: Double,
                         storeDiscountPercentage: Double,
                         priority: Double,
                         storeRemark: String,
                         customerRemark: String,
                         validateWithCMS: Boolean,
                         status: String,
                         deliveryCharge: Double,
                         cashHandlingCharge: Double,
                         payableAmount: Double,
                         totalAmount: Double,
                         interStateOrder: Boolean,
                         courierOrder: Boolean,
                         issue: String,
                         thirdPartyOrder: String,
                         customerCareNumber: String,
                         customerCareEmail: String,
                         updatedByName: String,
                         retailerName: String,
                         deltaReportedOn: String,
                         pharmacistSignatureId: String,
                         ref: Boolean
                       )



