#qa,stage, qa2
env=stage

qa.database.db=th008
qa_gometal.database.db=th141
qa3_gometal.database.db=th141
stage.database.db=th124
qa2.database.db=th032
prod.database.db=th141
api.print.curl=true

#customerInvoice , storeInvoice , picking
flowRequired = picking


########### order processing ###########
cmsOrderId =625403-6RW





####################CMS config ###################

#CARMENTA 300MG CAPSULE 15'S, DIGENE MINT FLAVOUR SUGAR FREE GEL 450ML
cart.medNames=DAROLAC CAPSULE
cart.totalMedicine = 1
cart.medQty=5
number.of.orders=1

#qa2 : 444443, 444440
#stage : 400039
#qa: 700035, 110019
#qa4 400083
pincode=400083
cmsNode=qa4